# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: [ '--maxkb=5000' ]
      - id: check-toml
      - id: check-yaml
#      - id: check-json # is replaced with check-json5 bellow
      - id: detect-private-key
      - id: end-of-file-fixer
      #      - id: requirements-txt-fixer
      #        exclude: ^requirements/.*$
      - id: trailing-whitespace
      - id: name-tests-test
        args: [ --pytest-test-first ]
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff
        args: ['--fix']
      - id: ruff-format
  -   repo: https://github.com/Yelp/detect-secrets
      rev: v1.5.0
      hooks:
        -   id: detect-secrets
            # exclude list of files
            exclude: |
              (?x)^(
              docs/windows_workflow/win_dotfiles/\.obsidian/plugins/.*/main\.js|
              docs/windows_workflow/win_dotfiles/.glzr/zebar/.*.html|

              )$
