name: env-cpu
dependencies:
  - python=3.9
  - git
  - pip
  - conda-forge::ninja
  - conda-forge::ffmpeg
  - conda-forge::gxx=11.4
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - torch==2.0.1
      - -r requirements-cpu.txt
