extend-include = ["*.ipynb"]
line-length = 100

# read more here https://docs.astral.sh/ruff/settings/#lintpydocstyle
[lint]
# Enable all `pydocstyle` rules, limiting to those that adhere to the Google convention via `convention = "google"`
select = [
    "D",
]
# On top of the Google convention, disable for ex `D417`, which requires documentation for every function parameter.
ignore = ["D100", "D103", "D417"]

[lint.pydocstyle]
# Use Google-style docstrings.
convention = "google"
